---
apiVersion: v1
offerings:
  - name: testing-deploy-arch-ibm-event-notifications
    kind: solution
    catalog_id: f64499c8-eb50-4985-bf91-29f9e605a433
    offering_id: 1f6f1af5-185e-4ae7-9b42-4c64e42728f6
    variations:
      - name: standard
        mark_ready: true
        install_type: fullstack
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
